spring:
  profiles:
    active: local

---

spring:
  profiles: default
  tomcat:
    ajp:
      port: 8009
      remoteauthentication: false
      enabled: true
  session:
  store-type:
  http:
    encoding:
      force: true
      force-request: true
      force-response: true
  messages:
    basename: messages/messages
    encoding: UTF-8
    always-use-message-format: false
    fallback-to-system-locale: true
  mvc:
    servlet:
      load-on-startup: 1
  #  mvc:
  #    view:
  #      prefix: /WEB-INF/view/
  #      suffix: .jsp
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 3MB
      location: /Users/peter/PRNumber/was/store/upload
      max-request-size: 10MB
      resolve-lazily: false
  activemq:
    broker-url: tcp://localhost:61616
    user:
    password:
    pool:
      enabled: true
    packages:
      trust-all: true
    queue: sdua.queue
  jackson:


---



spring.profiles: locallog
logging:
  file: ./logs
  #  pattern:
  #    #    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  #    #    file: "[%d{MM-dd HH:mm:ss}] %-5p [%t] %-17c{2}(%13F:%L) %3x - %m%n"
  #    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  #    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  #  #    dateformat: "[yyyy-MM-dd HH:mm:ss]"
  #  #    level: "%5p"
  level:
    root: info
    java:
      sql: debug
      sqlonly: debug
      sqltiming: debug
      audit: debug
      resultset: debug
    org.hibernate: warn
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.youngplussoft.sbdemo: debug
    org.apache.ibatis: trace
    java.sql: debug
    java.sql.Connection: info
    java.sql.Statement: info
    java.sql.PreparedStatement: debug
    java.sql.ResultSet: debug
    com.google.android.gcm.server: debug
    org.springframework.orm: warn
    org.springframework.core: warn
    org.springframework.beans: warn
    org.springframework.context: warn
    org.springframework.aop: warn
    org.springframework.web: info
    org.springframework.transaction: warn
    org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor: error
    org.springframework.data.redis.core.RedisConnectionUtils: warn
    org.springframework.web.servlet.mvc.method.annotation: trace
    org.springframework.web.servlet: info
    org.springframework.jdbc.core: warn
    org.apache.commons: info
    org.apache.activemq.transport: error
    org.springframework.jdbc.datasource.DataSourceTransactionManager: error
    org.apache.activemq.ActiveMQSession: error
    com.zaxxer.hikari: debug
    com.fasterxml.jackson.core: debug
    com.spring.ibatis: debug

---

spring:
  profiles: localenv
  redis:
    host: "localhost"
    port: 6379
    password: "pplus123#@!"
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
server:
  tomcat:
    basedir: ./logs
    uri-encoding: UTF-8
  port: 8080
  security:
    require-ssl: false

---

spring:
  profiles: jpa
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    database: mysql
    generate-ddl: false
    open-in-view: false
    show-sql: true
#    mapping-resources:
#    properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL57Dialect
      ddl-auto: validate
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  data:
    jpa:
      repositories:
#        bootstrap-mode:
        enabled: true
---

spring:
  profiles: localdb
  jpa-datasource:
    hikari:
      jdbc-url: "jdbc:mysql://localhost:3306/pplus?autoReconnection-true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul"
      driver-class-name: "com.mysql.cj.jdbc.Driver"
      username: 0soft
      password: 0soft
      connection-init-sql: "select 1 from dual"
      connection-test-query: "select 1 from dual"
#      schema:
      minimum-idle: 10
      idle-timeout: 600000
      auto-commit: true
      allow-pool-suspension: false
#      catalog:
#      data-source-j-n-d-i:
#      data-source-class-name:
      connection-timeout: 70000
      data-source-properties: "{password=<0soft>}"
      health-check-properties: "{}"
#      health-check-registry:
      initialization-fail-timeout: 1
      isolate-internal-queries: false
      leak-detection-threshold: 0
      max-lifetime: 1800000
      maximum-pool-size: 10
#      metric-registry: com.codahale.metrics.MetricRegistry
#      metrics-tracker-factory: com.zaxxer.hikari.metrics.MetricsTracker
      read-only: false
      register-mbeans: false
#      scheduled-executor:
      transaction-isolation: TRANSACTION_REPEATABLE_READ
      login-timeout: 70000
      pool-name: HikariPool1
      validation-timeout: 5000


---

spring:
  profiles: local
    - default
    - localenv
    - locallog
    - localdb
    - jpa
